#!/bin/bash
####################################################################################################
#
# FILENAME:     refresh-sandbox
#
# PURPOSE:      Refreshes a sandbox
#
# DESCRIPTION:  Refreshes a sandbox
#
# INSTRUCTIONS: Execute the following command from the root of your SFDX project directory.
#               ./dev-tools/refresh-sandbox
#
# JQ REQUIRED; TO INSTALL JQ:
# WINDOWS: curl -L -o /usr/bin/jq.exe https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
# MAC:     curl -L -o /usr/bin/jq.exe https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
####################################################################################################

sandboxName=$1
if [ -z "$sandboxName" ]; then
    echo "The SandboxName parameter must be provided, like so:"
    echo "./dev-tools/refresh-sandbox RMDev"
    echo "                              ^ this being the example SandboxName."
    exit 0
fi
exit 0
#
##
###
#### LOAD SHARED FUNCTIONS LIBRARY #################################################################
###
##
#
# Make sure that the shared-functions.sh script exists.
if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
  echo "\nFATAL ERROR: `tput sgr0``tput setaf 1`Could not load dev-tools/lib/shared-functions.sh.  File not found.\n"
  exit 1
fi

# Indicate the operation being carried out by this script.
REQUESTED_OPERATION="refresh-sandbox"

# Load the shared-functions.sh library.  This action will also cause the
# config variables from dev-tools/lib/local-config.sh to be loaded.
source `dirname $0`/lib/shared-functions.sh

refreshSandbox "$DEV_HUB_ALIAS" "$sandboxName"

exit 0

##END##